### GET Request 
GET https://jsonplaceholder.typicode.com/users/1
Accept: application/json

### POST Request (Create a New User)
POST https://lms-d0g5.onrender.com/api/auth/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "1234",
  "role": "teacher"
}

### POST Request (login User)
POST http://localhost:5000/admin/users/edit/:id
Content-Type: application/json

{"id": "67c6e83c3bb135517385d4eb"
    "name": "Jiya",
  "email": "jia@mail.com",
  "role": "student"
}

### PUT Request (Update User)
PUT https://jsonplaceholder.typicode.com/users/1
Content-Type: application/json

{
  "name": "John Updated",
  "email": "updated@example.com"
}

### DELETE Request (Remove User)
DELETE https://jsonplaceholder.typicode.com/users/1
